global_costmap:
        global_frame: map
        robot_base_frame: base_link
        update_frequency: 1.0
        publish_frequency: 0.2
        map_topic: "/map"
        static_map: true
        transform_tolerance: 2
        always_send_full_costmap: true
        track_unknown_space: true
        resolution: 0.02
        plugins:
         -
          name: static
          type: "costmap_2d::StaticLayer"
         -
          name: obstacles
          type: "costmap_2d::ObstacleLayer"
         -
          name: inflater
          type: "costmap_2d::InflationLayer"
        #inflater:
        #    cost_scaling_factor: 20.0
        #    inflation_radius: 0.17
